import { BrowserSettings, SecurityLevel, PrivacyStats, Workspace, ShieldState } from './types';
import { 
  Shield, 
  Lock, 
  EyeOff, 
  Trash2, 
  Wifi, 
  Globe, 
  Zap, 
  Moon, 
  Layout,
  Globe2,
  HardDrive,
  Cpu,
  Layers
} from 'lucide-react';

export const DEFAULT_SETTINGS: BrowserSettings = {
  httpsOnly: true,
  blockTrackers: true,
  blockFingerprinting: true,
  blockAnnoyances: true,
  autoDeleteData: true,
  vpnEnabled: false,
  vpnRegion: 'jordan',
  securityLevel: SecurityLevel.STRICT,
  theme: 'dark',
  showServoDebug: false,
  dataSaver: true,
  nightEconomy: false,
  predictivePreloading: true,
  dnsOverHttps: true,
  blockWebRtc: true,
  torIntegration: false,
  cookiePolicy: 'block-third-party',
  renderingBackend: 'hybrid',
  isolationMode: 'isolate'
};

export const DEFAULT_SHIELD_STATE: ShieldState = {
  isActive: true,
  stealthMode: false,
  currentUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Sanda/1.0',
  adsBlockedSession: 0,
  trackersBlockedSession: 0,
  cryptojackingBlockedSession: 0,
  lastThreatDetected: null,
  lastThreatLevel: 'None',
  dohProvider: 'local_rust_resolver',
  logs: []
};

export const DEFAULT_WORKSPACES: Workspace[] = [
  { id: 'personal', name: 'Personal', icon: 'coffee', color: 'bg-blue-500' },
  { id: 'work', name: 'Work', icon: 'briefcase', color: 'bg-orange-500' },
  { id: 'dev', name: 'Dev', icon: 'code', color: 'bg-purple-500' },
];

export const MOCK_STATS: PrivacyStats = {
  trackersBlocked: 14205,
  bandwidthSavedMB: 450,
  threatsPrevented: 12,
  fingerprintingAttempts: 843,
  annoyancesCrushed: 154
};

export const TRANSLATIONS = {
  en: {
    newTab: 'New Tab',
    searchOrUrl: 'Search or enter address',
    settings: 'Settings',
    privacyReport: 'Privacy Report',
    trackersBlocked: 'Trackers Blocked',
    annoyancesCrushed: 'Annoyances Crushed',
    dataSaved: 'Data Saved',
    fingerprints: 'Fingerprints Blocked',
    secureConnection: 'Secure Connection',
    securityLevel: 'Security Level',
    httpsOnly: 'Force HTTPS',
    vpn: 'Built-in VPN',
    appearance: 'Appearance',
    general: 'General',
    privacy: 'Privacy & Security',
    about: 'About Sanda',
    back: 'Back',
    forward: 'Forward',
    reload: 'Reload',
    stop: 'Stop',
    dashboard: 'Dashboard',
    customize: 'Customize',
    save: 'Save Changes',
    simulatedContent: 'Bare-Metal Architecture Visualization',
    rustEngine: 'Core: Rust',
    webfEngine: 'UI: WebF (Flutter)',
    connected: 'Connected (Encrypted)',
    disconnected: 'Disconnected',
    strictMode: 'Strict Mode',
    standardMode: 'Standard Mode',
    maxMode: 'Max Privacy',
    tabFrozen: 'Tab Suspended',
    tabFrozenDesc: 'This tab was frozen to save RAM. Click to wake it up.',
    wakeTab: 'Wake Tab',
    secureLogin: 'Secure Auth Bridge',
    secureLoginDesc: 'Authentication is handled by the Flutter AppAuth bridge. The browser engine never sees your password.',
    continueWithAuth: 'Launch AppAuth Bridge',
    mobileView: 'Mobile Simulator',
    pipMode: 'Smart PiP Active',
    pipDesc: 'Video popped out automatically',
    annoyanceToast: 'Cookie Banner Auto-Dismissed',
    servoDebug: 'Core Engine Tools',
    rustPanic: 'Rust Core Panic!',
    rustPanicDesc: 'The secure Rust core encountered a memory safety violation and halted execution to prevent leakage.',
    respawnProcess: 'Respawn Rust Core',
    displayList: 'Display List (WebRender)',
    parallelLayout: 'Parallel Layout Threads',
    installPwa: 'Install App (PWA)',
    pwaInstalled: 'App Installed Successfully',
    smartInput: 'Smart Arabic Input',
    nightEconomy: 'Night Economy Mode',
    dataSaver: 'Smart Data Saver (60%)',
    preloading: 'Predictive Preloading',
    vpnRegion: 'VPN Region',
    torMode: 'Tor Circuit Integration',
    webRtc: 'Block WebRTC (IP Leak)',
    doh: 'DNS over HTTPS',
    cookies: 'Cookie Policy',
    rustScore: 'Security Score',
    authBridge: 'Identity & Auth Bridge',
    authBridgeDesc: 'Manage OIDC/OAuth2 sessions isolated from the webview.',
    renderingBackend: 'Rendering Engine',
    isolationMode: 'Process Isolation',
    architecture: 'Architecture',
    privacyShield: 'Privacy Shield',
    stealthMode: 'Stealth Mode',
    cryptojacking: 'Cryptojacking',
    dohActive: 'DoH Active',
    shieldActive: 'Shield Active',
    threatDetected: 'Threat Detected',
    userAgent: 'User Agent Identity',
    blocked: 'Blocked',
    cookieOptions: {
        allow: 'Allow All',
        blockThird: 'Block Third-Party',
        blockAll: 'Block All (Strict)'
    },
    backendOptions: {
        webf: 'WebF Only (Fastest)',
        servo: 'Servo Only (Rust)',
        hybrid: 'Hybrid (Smart Switch)'
    },
    isolationOptions: {
        thread: 'Thread (Light)',
        isolate: 'Dart Isolate (Balanced)',
        process: 'OS Process (Heavy)'
    },
    regions: {
        jordan: 'Amman, Jordan',
        dubai: 'Dubai, UAE',
        saudi: 'Riyadh, KSA',
        europe: 'Frankfurt, DE'
    },
    featureDesc: {
        https: 'Forces all connections to use secure HTTPS encryption.',
        vpn: 'Route traffic through our secure, no-log privacy network.',
        tracker: 'Blocks analytical scripts (Google, FB) and invisible pixels.',
        fingerprint: 'Prevents sites from identifying your device config.',
        delete: 'Automatically wipes cookies/history on exit.',
        annoyance: 'Auto-closes cookie banners and newsletter popups.',
        nightEconomy: 'Reduces blue light and battery usage by 40%.',
        dataSaver: 'Compresses images/CSS via WebF engine.',
        tor: 'Route traffic through Tor nodes to bypass censorship.',
        webRtc: 'Prevents real IP leakage during streaming/P2P.',
        doh: 'Encrypts DNS requests to prevent ISP spying.'
    }
  },
  ar: {
    newTab: 'علامة تبويب جديدة',
    searchOrUrl: 'ابحث أو أدخل العنوان',
    settings: 'الإعدادات',
    privacyReport: 'تقرير الخصوصية',
    trackersBlocked: 'متعقبات محظورة',
    annoyancesCrushed: 'إزعاجات أزيلت',
    dataSaved: 'بيانات موفرة',
    fingerprints: 'بصمات رقمية محظورة',
    secureConnection: 'اتصال آمن',
    securityLevel: 'مستوى الأمان',
    httpsOnly: 'فرض HTTPS',
    vpn: 'VPN مدمج',
    appearance: 'المظهر',
    general: 'عام',
    privacy: 'الخصوصية والأمان',
    about: 'عن ساندا',
    back: 'رجوع',
    forward: 'تقدم',
    reload: 'تحديث',
    stop: 'إيقاف',
    dashboard: 'لوحة التحكم',
    customize: 'تخصيص',
    save: 'حفظ التغييرات',
    simulatedContent: 'محاكاة المعمارية المجردة (Bare-Metal)',
    rustEngine: 'النواة: Rust',
    webfEngine: 'الواجهة: WebF (Flutter)',
    connected: 'متصل (مشفر)',
    disconnected: 'غير متصل',
    strictMode: 'الوضع الصارم',
    standardMode: 'الوضع القياسي',
    maxMode: 'خصوصية قصوى',
    tabFrozen: 'تم تجميد التبويب',
    tabFrozenDesc: 'تم إيقاف هذا التبويب مؤقتاً لتوفير الذاكرة. انقر للاستيقاظ.',
    wakeTab: 'إيقاظ التبويب',
    secureLogin: 'جسر المصادقة الآمن',
    secureLoginDesc: 'تتم المصادقة عبر جسر Flutter AppAuth المعزول. لا يرى محرك المتصفح كلمة المرور الخاصة بك أبدًا.',
    continueWithAuth: 'تشغيل جسر AppAuth',
    mobileView: 'محاكي الجوال',
    pipMode: 'فيديو عائم ذكي',
    pipDesc: 'تم إخراج الفيديو تلقائياً',
    annoyanceToast: 'تم إغلاق لافتة الكوكيز تلقائياً',
    servoDebug: 'أدوات المحرك (Core)',
    rustPanic: 'انهيار نواة Rust!',
    rustPanicDesc: 'واجهت نواة Rust الآمنة انتهاكًا لسلامة الذاكرة وأوقفت التنفيذ لمنع التسرب.',
    respawnProcess: 'إعادة تشغيل النواة',
    displayList: 'قائمة العرض (WebRender)',
    parallelLayout: 'خيوط التخطيط المتوازي',
    installPwa: 'تثبيت التطبيق (PWA)',
    pwaInstalled: 'تم تثبيت التطبيق بنجاح',
    smartInput: 'إدخال عربي ذكي',
    nightEconomy: 'وضع الاقتصاد الليلي',
    dataSaver: 'توفير البيانات الذكي (60%)',
    preloading: 'التحميل المسبق التنبؤي',
    vpnRegion: 'منطقة VPN',
    torMode: 'دمج شبكة Tor (ضد الرقابة)',
    webRtc: 'حظر WebRTC (تسريب IP)',
    doh: 'تشفير DNS (DoH)',
    cookies: 'سياسة ملفات تعريف الارتباط',
    rustScore: 'نقاط الأمان (Rust)',
    authBridge: 'الهوية وجسر المصادقة',
    authBridgeDesc: 'إدارة جلسات OIDC/OAuth2 بمعزل عن عرض الويب.',
    renderingBackend: 'محرك العرض',
    isolationMode: 'عزل العمليات',
    architecture: 'البنية المعمارية',
    privacyShield: 'درع الخصوصية',
    stealthMode: 'وضع التمويه',
    cryptojacking: 'تعدين العملات',
    dohActive: 'DoH نشط',
    shieldActive: 'الدرع نشط',
    threatDetected: 'تم كشف تهديد',
    userAgent: 'هوية المتصفح (User Agent)',
    blocked: 'محجوب',
    cookieOptions: {
        allow: 'السماح للكل',
        blockThird: 'حظر الطرف الثالث',
        blockAll: 'حظر الجميع (صارم)'
    },
    backendOptions: {
        webf: 'WebF فقط (الأسرع)',
        servo: 'Servo فقط (Rust)',
        hybrid: 'هجين (تبديل ذكي)'
    },
    isolationOptions: {
        thread: 'خيط (خفيف)',
        isolate: 'معزول Dart (متوازن)',
        process: 'عملية نظام (ثقيل)'
    },
    regions: {
        jordan: 'عمان، الأردن',
        dubai: 'دبي، الإمارات',
        saudi: 'الرياض، السعودية',
        europe: 'فرنكتفورت، ألمانيا'
    },
    featureDesc: {
        https: 'يفرض استخدام تشفير HTTPS الآمن لجميع الاتصالات.',
        vpn: 'توجيه حركة المرور عبر شبكتنا الآمنة التي لا تحتفظ بالسجلات.',
        tracker: 'يحظر نصوص Google وFacebook التحليلية ووحدات البكسل.',
        fingerprint: 'يمنع المواقع من التعرف على تكوين جهازك.',
        delete: 'مسح ملفات تعريف الارتباط/السجل تلقائيًا عند الخروج.',
        annoyance: 'يغلق لافتات الكوكيز والنوافذ المنبثقة تلقائياً.',
        nightEconomy: 'يقلل الضوء الأزرق واستهلاك البطارية بنسبة 40%.',
        dataSaver: 'ضغط الصور والملفات عبر محرك WebF.',
        tor: 'توجيه الاتصال عبر عقد Tor لتجاوز الرقابة والحجب.',
        webRtc: 'يمنع تسرب عنوان IP الحقيقي أثناء البث.',
        doh: 'يشفر طلبات DNS لمنع مزود الخدمة من التجسس.'
    }
  }
};

export const SETTING_SECTIONS = [
  { id: 'shield', icon: Shield, labelEn: 'Privacy Shield', labelAr: 'درع الخصوصية' },
  { id: 'architecture', icon: Layers, labelEn: 'Architecture', labelAr: 'المعمارية' },
  { id: 'privacy', icon: EyeOff, labelEn: 'Privacy', labelAr: 'الخصوصية' },
  { id: 'security', icon: Lock, labelEn: 'Security', labelAr: 'الأمان' },
  { id: 'identity', icon: Globe, labelEn: 'Identity', labelAr: 'الهوية' },
  { id: 'appearance', icon: Layout, labelEn: 'Appearance', labelAr: 'المظهر' },
  { id: 'storage', icon: HardDrive, labelEn: 'Storage', labelAr: 'التخزين' },
];